import { useState } from 'react'
import { CircleUserRound, Menu, X } from 'lucide-react'

const videoUrl = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260715_082433_69699cf8-444b-4484-93cc-053e57896dfd.mp4'
const avatars = ['https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100', 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100', 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100', 'https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&w=100']
const navLinks = ['Home', 'Our Approach', 'Healing Methods']
const hrefFor = (label: string) => `#${label.toLowerCase().replaceAll(' ', '-')}`

function Logo() { return <svg className="h-8 w-8 fill-white md:h-9 md:w-9" viewBox="0 0 256 256" aria-label="Vibrant Wellness logo"><path d="M 128 128 C 198.692 128 256 185.308 256 256 L 151.883 256 C 149.812 220.307 120.213 192 84 192 C 47.787 192 18.188 220.307 16.117 256 L 0 256 C 0 185.308 57.308 128 128 128 Z M 104.117 0 C 106.188 35.694 135.787 64 172 64 C 208.213 64 237.812 35.694 239.883 0 L 256 0 C 256 70.692 198.692 128 128 128 C 57.308 128 0 70.692 0 0 Z" /></svg> }
function TrianglePattern() { const dots = [[9,0],[6,4],[12,4],[3,8],[9,8],[15,8],[0,12],[6,12],[12,12]]; return <span className="relative block h-5 w-5 shrink-0" aria-hidden="true">{dots.map(([left, top]) => <i key={`${left}-${top}`} className="absolute h-[2.5px] w-[2.5px] bg-white/60" style={{ left, top }} />)}</span> }
function GridPattern() { return <span className="grid h-5 w-5 shrink-0 grid-cols-3 content-center gap-[2px]" aria-hidden="true">{Array.from({ length: 9 }, (_, i) => <i key={i} className={`h-1 w-1 rounded-[1px] ${(Math.floor(i / 3) + i) % 2 === 0 ? 'bg-white/60' : 'bg-white/0'}`} />)}</span> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main className="relative isolate h-[100dvh] min-h-[600px] overflow-hidden bg-[#07110b]">
    <video className="absolute inset-0 -z-20 h-full w-full object-cover" autoPlay loop muted playsInline aria-hidden="true"><source src={videoUrl} type="video/mp4" /></video><div className="absolute inset-0 -z-10 bg-black/15" />
    <nav className="relative z-20 flex items-center justify-between px-5 pt-6 sm:px-8 sm:pt-8 md:px-16 lg:px-20" aria-label="Main navigation"><a href="#home" aria-label="Vibrant Wellness home"><Logo /></a><div className="liquid-glass hidden items-center gap-7 rounded-full px-8 py-3 md:flex">{navLinks.map((link, index) => <a key={link} href={hrefFor(link)} className={`relative z-10 text-sm font-medium transition-opacity ${index === 0 ? 'text-white' : 'text-white/70 hover:opacity-100'}`}>{link}</a>)}</div><div className="liquid-glass hidden h-10 w-10 items-center justify-center rounded-full md:flex"><CircleUserRound className="relative z-10 h-5 w-5 text-white/80" strokeWidth={1.5} /></div><button onClick={() => setMenuOpen(!menuOpen)} className="liquid-glass z-50 flex h-10 w-10 items-center justify-center rounded-full md:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}><Menu className={`absolute h-5 w-5 transition-all duration-300 ${menuOpen ? 'rotate-90 scale-0 opacity-0' : 'rotate-0 scale-100 opacity-100'}`} strokeWidth={1.5} /><X className={`absolute h-5 w-5 transition-all duration-300 ${menuOpen ? 'rotate-0 scale-100 opacity-100' : '-rotate-90 scale-0 opacity-0'}`} strokeWidth={1.5} /></button></nav>
    <div className={`fixed inset-0 z-10 flex items-center justify-center bg-black/80 backdrop-blur-xl transition-opacity duration-500 ease-out md:hidden ${menuOpen ? 'pointer-events-auto opacity-100' : 'pointer-events-none opacity-0'}`}><div className={`flex flex-col items-center gap-8 transition-transform duration-500 ease-out ${menuOpen ? 'translate-y-0' : '-translate-y-8'}`}>{navLinks.map(link => <a key={link} href={hrefFor(link)} onClick={() => setMenuOpen(false)} className="text-2xl font-medium text-white">{link}</a>)}<div className="mt-2 flex items-center gap-3"><span className="liquid-glass flex h-10 w-10 items-center justify-center rounded-full"><CircleUserRound className="relative z-10 h-5 w-5 text-white/80" strokeWidth={1.5} /></span><span className="text-sm font-light text-white/60">Account</span></div></div></div>
    <section id="home" className={`relative z-10 mx-auto flex h-[calc(100%-56px)] max-w-[1600px] flex-col justify-between px-5 pb-7 transition-all duration-300 sm:h-[calc(100%-64px)] sm:px-8 sm:pb-9 md:h-[calc(100%-68px)] md:px-16 lg:px-20 ${menuOpen ? 'pointer-events-none opacity-0 md:pointer-events-auto md:opacity-100' : 'opacity-100'}`}><div className="mt-14 max-w-2xl sm:mt-20 md:mt-28"><div className="liquid-glass mb-5 inline-flex items-center gap-2.5 rounded-full px-3 py-1.5 sm:mb-6 sm:gap-3 sm:px-4 sm:py-2"><div className="relative z-10 flex -space-x-2">{avatars.map((src, i) => <img key={src} src={src} alt="Wellness community member" className="h-5 w-5 rounded-full border-2 border-white/20 object-cover sm:h-6 sm:w-6" style={{ zIndex: avatars.length - i }} />)}</div><span className="relative z-10 text-xs font-light text-white/80 sm:text-sm">our path to natural wellness</span></div><h1 className="inline text-4xl font-normal leading-[1.05] tracking-[-0.05em] text-white sm:text-5xl md:text-6xl lg:text-7xl">Heal Your Body<br />Naturally</h1><p className="mt-4 text-sm font-light text-white/70 sm:mt-5 sm:text-base md:text-lg">Holistic wellness. Transformative results.</p><a href="#begin" className="liquid-glass mt-6 inline-flex rounded-full px-6 py-3 text-sm font-medium text-white transition duration-300 hover:bg-white/10 sm:mt-8 sm:px-7 sm:py-3.5"><span className="relative z-10">Begin Your Journey</span></a></div><div className="flex items-end gap-6 sm:gap-10 md:gap-16"><div className="flex items-start gap-3 sm:gap-4"><TrianglePattern /><div><p className="text-xl font-normal text-white sm:text-2xl md:text-3xl">48 Hours</p><p className="mt-1 text-xs font-light text-white/60 sm:text-sm">Initial Consultation</p></div></div><div className="flex items-start gap-3 sm:gap-4"><GridPattern /><div><p className="text-xl font-normal text-white sm:text-2xl md:text-3xl">Initial Consultation</p><p className="mt-1 text-xs font-light text-white/60 sm:text-sm">Healing Sessions</p></div></div></div></section>
  </main>
}
export default App
